---
- include: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Logstash.
  apt: pkg=logstash state=present

- include: plugins.yml

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
  enabled: "{{ logstash_enabled_on_boot }}"
  when: logstash_enabled_on_boot == true