---
- name: Ensure dependency is installed (Ubuntu).
  apt: name=apt-transport-https state=present

- name: Debian - Add Elasticsearch repository key
  become: yes
  apt_key: url="{{ ls_apt_key_url }}" state=present
  when: ls_use_repository and ls_apt_key_url

- name: Debian - Add Elasticsearch repository
  become: yes
  apt_repository: repo={{ ls_apt_url }} state=present
  when: ls_use_repository