- name: ELK Stack Single Node
  hosts: localhost
  become: true
  roles:
    - role: elastic.elasticsearch
    - role: logstash
    - role: kibana
    - role: nginxinc.nginx
    - role: nginx-elk-config
  vars:
      es_instance_name: "{{ es_instance_name }}"
      es_data_dirs:
        - "/data/elasticsearch/data"
      es_log_dir: "/data/elasticsearch/logs"
      es_config: 
        node.name: "{{ es_cluster_node_name }}"
        node.master: true
        cluster.name: "{{ es_cluster_name }}"
      es_enable_xpack: true
      es_api_basic_auth_username: "{{ es_cluster_username }}"
      es_api_basic_auth_password: "{{ es_cluster_password }}"
      es_version: 6.3.2
      type: openssource